### ISSUE TITLE
🐞 - `Number` with `decimalZeroPadding=true` should erase everything on `.00`

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/maskito#1085]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://maskito.dev/kit/number/API?decimalZeroPadding=true&precision=2

### Case 1

1. Open https://maskito.dev/kit/number/API?decimalZeroPadding=true&precision=2
2. Type `0.12`
3. Select all (e.g. `Ctrl` + `A`)
4. Press `Backspace`

**Actual**: Empty textfield ✅
**Expected**: Empty textfield 

### Case 2

1. Open https://maskito.dev/kit/number/API?decimalZeroPadding=true&precision=2
2. Type `0.12`
3. `0.12|` => Backspace * 3 => `0|.00` => Backspace => ???

**Actual**: `.00` ❌
**Expected**: Empty textfield 

### Maskito version

2.0.2

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by KrollikRoddzer** [comment]
<img width="509" alt="Снимок экрана 2024-04-05 в 13 51 55" src="https://github.com/taiga-family/maskito/assets/102649815/2940edb3-20c4-4167-b294-845b49cf0f62">

Should the result be `empty string` or `',|0000'` in this case?

@nsbarsukov @waterplea @vladimirpotekhin
