### ISSUE TITLE
🐞 - Min option not working for Date kit

### ISSUE THREAD

**Issue by rmlira** [taiga-family/maskito#1152]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/udcnha?file=mask.ts

## Case 1
Open https://stackblitz.com/edit/udcnha?file=mask.ts
Type 01.01.200
Press Tab
Actual: 01.01.200
Expected: 01.01.2000 = Min value in the options

### Maskito version

2.1.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by rmlira** [comment]
> @rmlira invalid repro link

Fixed, thanks. I have also tried directly in the documentation page: https://maskito.dev/kit/date#min-max same result

**Comment by nsbarsukov** [comment]
@rmlira Hello!

Actually, it is expected bahaviour
https://github.com/taiga-family/maskito/blob/f7f357bf3882a892e95850a3e12d5bb102e54d8e/projects/kit/src/lib/processors/min-max-date-postprocessor.ts#L39

Date-related masks do not validate min/max constraints for incomplete date strings.

___

However, you can augment built-in mask with any custom logic using custom plugin.

```ts
import type { MaskitoOptions, MaskitoPlugin } from '@maskito/core';
import { Maskito } from '@maskito/core';
import { maskitoDateOptionsGenerator, maskitoEventHandler } from '@maskito/kit';

const dateOptions = maskitoDateOptionsGenerator({
  mode: 'dd/mm/yyyy',
});

const onBlurPlugin: MaskitoPlugin = maskitoEventHandler('blur', (element) => {
  if (element.value.length < 'dd/mm/yyyy'.length) {
    // any your custom logic
    // element.value = ...
  }
});

const maskitoOptions: MaskitoOptions = {
  ...dateOptions,
  plugins: [...dateOptions.plugins, onBlurPlugin],
};

const input: HTMLInputElement = document.querySelector('input')!;

const maskedInput = new Maskito(input, maskitoOptions);
```
