### ISSUE TITLE
📚 - Time/Date uses undocumented kind of placeholder

### ISSUE THREAD

**Issue by mduft** [taiga-family/maskito#1159]
### What is the affected URL?

https://maskito.dev/kit/time

### Description

When looking at the time mask in the example, if the field receives the focus there is a placeholder in grey - which is *NOT* part of the input's value - whereas the maskitoWithPlaceholder will make the placeholder characters the same color and part of the input's text.

I need this kind of placeholder :D And the documentation does not give a hint on how to do it. Also when opening the stackblitz example, the placeholder is *not* there :(

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
This placeholder is not part of **Maskito**, yep.

Maskito does **not** add any additional elements to DOM. It just listens native events of `<input />` / `<textarea />` elements and controls their value.
In the documentation this gray placeholder is just additional html-element which is positioned on the top `<input />` element.

**Maskito's** documentation uses **Taiga UI** to show fancy textfields.
**Taiga UI** has [`Input`](https://taiga-ui.dev/components/input) component which provides this awesome gray placeholder (`[tuiTextfieldFiller]` property).
