### ISSUE TITLE
🚀 - Allow both comma and period to insert `decimalSeparator` even when `thousandSeparator` is set to one of them.

### ISSUE THREAD

**Issue by mduft** [taiga-family/maskito#1168]
### Which package(s) are relevant/related to the feature request?

@maskito/kit

### Description

Right now when I don't explicitly set a `thousandSeparator` (which is never entered manually (?), only shown when appropriate), I can use comma and and period to insert the `decimalSeparator`, no matter what it is set to.

However as soon as I set the `thousandSeparator` to e.g. `.`, I can only use `,` to enter the `decimalSeparator`.

We're running in environments where we cannot influence the keyboard layout(s) of the user, but each application user (on the same machine) can have different locale settings. Thus numpad `.` will always deliver a `.` or a `,`, but the applicaiton must understand that no matter the application setting.

If this is not scope of maskito, any pointers on how to work around this would be appreciated.

**Comment by waterplea** [comment]
This is a bit sketchy — the argument of thousand separator never being entered manually is an assumption. I can envision some old lady entering sum exactly as it is shown on her documents to pay utilities bill or something like that. I don't think we should change the current behavior. Currently we support a set of decimal separators to be treated equally when entered and it works unless it matches the thousand separator. I can only advice to use a different thousand separator. Not using dots or commas to group digits like that has been an official recommendation of International Bureau of Weights and Measures for over 70 years now, as well by ISO and many other international groups concerned with formatting. So my advice would be to just use spaces as a delimiter if you want to support multiple locales, as it is both internationally recognized format and a sane common ground for people from all over the world.

**Comment by waterplea** [comment]
@nsbarsukov would you have an advice regarding some pre/post processor that people can employ if they still want to do this?

**Comment by mduft** [comment]
Thanks for your thorough thoughts - makes sense to me :D We will discuss this internally, but I'm unsure whether we can get rid of the requirement - so advice would still be greatly appreciated :)

**Comment by nsbarsukov** [comment]
@mduft Sorry for late response!

The only advise I can give you – use `preprocessor` / `postprocessor` and put all your complex logic inside it.
https://maskito.dev/core-concepts/processors

You can explore the following preprocessor and create something similar to it:
https://github.com/taiga-family/maskito/blob/ec8628467814cff7dfae22668370236f402d8146/projects/kit/src/lib/masks/number/processors/pseudo-character-preprocessor.ts#L5-L10

**Comment by ggomarighetti** [comment]
I would like to reopen this issue, in Argentina as well as in most of Latin America we have keyboard layouts that bring the dot in the numpad, even though our number system uses the comma for decimals [wiki](https://en.wikipedia.org/wiki/Decimal_separator#Conventions_worldwide), even the windows settings include the comma as the decimal separator but it only works in desktop applications like Excel or similar spreadsheet processors.

I'm not saying that it should become a library standard, nor that it should be mandatory for new versions, but, a feature flag that can disable the feature that was introduced to skip these characters would solve the problem for both worlds. https://github.com/taiga-family/maskito/pull/390

Continuing with @waterplea  example, if the developer decides so, the granny who uses his application will be able to write as she sees the numbers on her bill, or she will have to double check what she writes. And it would avoid having to rewrite or reimplement the library processors as proposed by @nsbarsukov  which could also serve or solve the problems to more than one instead of the individual ones (as is the case).

**Comment by ggomarighetti** [comment]
I ended up making this pre-processor which correctly replaces when the user enters the specific character I am interested in and converts it to the decimal separator I use, without affecting the operation of the rest of the mask.

If I could reopen this issue and send it as a pullrequest, it would be the solution to the problems, and activate it in any case with a flag that could be decimalPseudoSeparatorsForce?

```
        ({ elementState, data }, actionType) => {
          const { value, selection } = elementState;

          if (actionType === "insert" && data === ".") {
            const [from, to] = selection;

            return {
              elementState: {
                selection,
                value: value.slice(0, from) + "," + value.slice(to),
              },
              data: ",",
            };
          }

          return {
            elementState: {
              selection: selection,
              value: value,
            },
            data: data,
          };
        },
````

**Comment by waterplea** [comment]
@nsbarsukov maybe we can make a `maskitoReplace('.', ',')` universal preprocessor that replaces one character with another upon entry? That would solve this case and might also prove useful in some other situations. Just need to mention in the docs in bold that it only works upon typing, not when you paste a whole string or something.

**Comment by nsbarsukov** [comment]
> [@nsbarsukov](https://github.com/nsbarsukov) maybe we can make a `maskitoReplace('.', ',')` universal preprocessor that replaces one character with another upon entry? That would solve this case and might also prove useful in some other situations. Just need to mention in the docs in bold that it only works upon typing, not when you paste a whole string or something.

@waterplea 
The task can be completed by the rather simple preprocessor:

```ts
function replaceDuringTyping(from: string, to: string): MaskitoPreprocessor {
  return ({ elementState, data }) => ({
    elementState,
    data: data.length === 1 ? data.replace(from, to) : data,
  });
}
```

It rather specific and no need to publish it to public API.

Explore more: https://stackblitz.com/edit/maskito-issue-1168
