### ISSUE TITLE
🚀 - `Time`, `DateTime` support AM/PM time formats including input of 'am'/'pm'

### ISSUE THREAD

**Issue by mduft** [taiga-family/maskito#1169]
### Which package(s) are relevant/related to the feature request?

@maskito/kit

### Description

Currently only 24 hour format works out of the box.

I noticed that there is a possibility to override the max values for individual segments, but I still cannot enter 'am' or 'pm' in the input field.

**Comment by KrollikRoddzer** [comment]
### Rearch ###
While researching different fields for time entry I was able to find two different approaches.

The **first** is to focus on a specific segment and edit it further. The **second** is when you can select in a separate am/pm field.

First example: https://mui.com/x/react-date-pickers/adapters-locale/#with-luxon
Second example: https://m3.material.io/components/time-pickers/overview#453a1694-0037-45f8-9421-8899bde1b6ea

### Specifications of the new feature: ###
* Supported masks: `"HH FF"`, `"HH:MM FF"`, `"HH:MM.MSS FF"`

* In the initial state, as long as the user has **not entered anything**, there will be `AM` in the **focused** input field. If the input **field is empty** and **out of focus**, it will be `empty`.
* Regardless of where the cursor is, the up-down arrows will change `AM` to `PM` and vice versa.
* When the cursor is at the end of numeric time segments (`HH:MM| FF` or `HH:MM |FF`), pressing `a/A` will expose `AM`, pressing `p/P` will expose `PM`.
* AM and PM cannot be erased, nor can the cursor be moved to them. The maximum cursor position will be: `HH:MM |FF`.

**Comment by ColinFrick** [comment]
Is there any progress on this feature?

Thanks for the great work! The lib looks really promising.

**Comment by nsbarsukov** [comment]
@ColinFrick 
Unfortunately, this feature is still part of our backlog ((
