### ISSUE TITLE
🚀 - `Time` &  `DateTime` support increament / decreament of time segment via `ArrowUp` / `ArrowDown`

### ISSUE THREAD

**Issue by mduft** [taiga-family/maskito#1170]
### Description

*Additionally* to the already present (really, really nice!) input handling it would be nice to have cursor key handling while editing. Whet I thought of here:

Cursor Right: Move to and select the next group, e.g. if the cursor is at 'HH' -> jump to 'MM'
Cursor Left: Move to and select the next group, e.g. if the cursor is at 'MM' -> jump to 'HH'
Cursor Up: Increment the group where the cursor is at, e.g. MM = 08 -> MM = 09.
Cursor Down: Decrement the group where the cursor is at.

Let me know what you think about this :)

**Comment by nsbarsukov** [comment]
@mduft Hello!

Your feature request includes two independent features.

The first one (cursor selection of the whole time group) is rather specific and and its robust implementation can be too difficult. I am not sure that we are ready to implement it now.

As for the second feature (increment/decrement time segment via `ArrowUp` / `ArrowDown`), it sounds good!
Thanks for you suggestion. I think we can create plugin (which listens `keydown` event) and add it to built-in `Time` and `DateTime` mask.

**Comment by mduft** [comment]
Sounds good to me - maybe I can come up with a selection plugin and share it here in case I manage to do it :D

**Comment by waterplea** [comment]
Sounds like you are trying to reinvent `input type="time"` :) It's supported by Safari 14.1+, all our apps must support Safari 13 so we haven't looked into using it yet, but it might work for you.

**Comment by mduft** [comment]
Well yes and no. In our environment we have little to no control over the browser used, but still need to be able to switch locale (language, separators, formats) inside the application depending on the user. HTML controls tend to rely on browser settings, so it would be impossible for us to set formats, and most importantly we don't have any control over the time (or date, ...) popups to select a time (there are "cancel", "apply", etc. buttons which require translation).

**Comment by nsbarsukov** [comment]
@KrollikRoddzer

1. Add `step` / `timeStep` parameters for `Time` / `DateTime`.
Default value is `0` (feature is disabled).

2. Create internal `createTimeSegmentSteppingPlugin(step: number)` (listen to `keydown`)
3. If `step` / `timeStep` > `0` => enable this internal plugin
