### ISSUE TITLE
🚀 - Numeric input with max and precision: when inputting don't jump to max, instead add decimalSeparator

### ISSUE THREAD

**Issue by mduft** [taiga-family/maskito#1171]
### Which package(s) are relevant/related to the feature request?

@maskito/kit

### Description

In a numeric input with `max` (e.g. 99,99) *and* `precision` (e.g. 2) set, it would be nice to be able to "just" type '1234' and end up with '12,34' instead of '99,99'. The user needs to manually add the decimal separator. I have implemented *something* with my still limited knowledge :) Could be part of the kit? Pretty sure the code can be improved *a lot* :D maybe its not even good at all, feedback more than welcome!

```ts
import { MaskitoPlugin, maskitoUpdateElement } from '@maskito/core';

export function maskitoAutoDecimal(
  maxLength: number,
  decimalSeparator: string,
  thousandSeparator: string
): MaskitoPlugin {
  return (element) => {
    const listener = (): void => {
      const value = element.value;

      element.addEventListener(
        'beforeinput',
        (event) => {
          const iev = event as InputEvent;
          if (
            iev.data?.length &&
            value.replace(new RegExp(`${thousandSeparator}`), '').length ===
              maxLength
          ) {
            maskitoUpdateElement(element, value + decimalSeparator + iev.data);
          }
        },
        { once: true }
      );
    };

    element.addEventListener('beforeinput', listener, true);
    return () => element.removeEventListener('beforeinput', listener, true);
  };
}

```

**Comment by waterplea** [comment]
Sounds like you want the following behavior, often seen in acquiring terminals and such devices:
```
1 -> 0,01
2 -> 0,12
3 -> 1,23
4 -> 12,34
```
So it's not really about the `max`. Is that right?

**Comment by mduft** [comment]
Not quite. The integer part of the number should still be the first thing entered:

1 -> 1
2 -> 12
3 -> 12,3
4 -> 12,34

(with a `max` of 99,99 for example). What I *actually* want is to specify both the length of the integer part, and the length of the fraction part. I do this currently, by specifying the `max` using something like this: `'9'.repeat(integerLength) + '.' + '9'.repeat(fractionLength)`.

**Comment by waterplea** [comment]
Well, that behavior doesn't make much sense to me, I don't think we will be adding it to Maskito. This basically requires the user to know the digits limit on the integer part and is only helpful when the number you are trying to enter has the same order of magnitude. Sounds like a lot of work on the developer side and a lot of cognitive load on the user side only to save you an explicit decimal separator keypress.

**Comment by mduft** [comment]
Agreed that this is not your everyday-number-input ... :D We're working on industrial application for small devices (industrial android devices). Those are used in areas where e.g. warehouse workers punch in weights all day. Combined with a filler that clearly shows them how many digits they are allowed to enter, this improves speed a lot (not having unneccessary key presses on a device with a sub-optimal keyboard in the first place. They still have to punch in the separator in case the number is shorter than expected though of course.

**Comment by waterplea** [comment]
Sounds like the approach I described could be helpful to them, it might be easier to punch double zeros when there is no decimal part than hitting a decimal separator. That is, of course, if there is a known precision. Like the acquiring terminals I mentioned, where you enter a sum of money so you know there are 2 digits for cents. That's probably why they are designed this way.

**Comment by mduft** [comment]
After some discussion we do agree that your suggestion is more logical. However ... :D We have a huge legacy application with thousand of users that are used to doing it that way in our legacy Java UIs. This *unfortunately* weighs heavier :| But we are fine with having our own plugin that *mostly* fixes the issue for us.

```
export function maskitoAutoDecimal(
  maxLength: number,
  decimalSeparator: string,
  thousandSeparator: string
): MaskitoPlugin {
  return (element) => {
    const listener = (): void => {
      const value = element.value;

      // FIXME: this only works if there is no separator (and stuff behind the separator).
      // it is unfortunately not possible to get the current carret position from the input
      // as *other* maskito handling modifies that position (it seems).

      element.addEventListener(
        'beforeinput',
        (event) => {
          const iev = event as InputEvent;
          const noSep = value.replace(new RegExp(`${thousandSeparator}`), '');
          const hasSelection =
            (element.selectionEnd || 0) - (element.selectionStart || 0) > 0;
          if (
            iev.data?.length &&
            noSep.length === maxLength &&
            !hasSelection &&
            !value.includes(decimalSeparator)
          ) {
            maskitoUpdateElement(element, value + decimalSeparator + iev.data);
          }
        },
        { once: true }
      );
    };

    element.addEventListener('beforeinput', listener, true);
    return () => element.removeEventListener('beforeinput', listener, true);
  };
}
```

This works, however has an issue; when there already *is* a decimal separator in the value and I place the cursor before the decimal separator somewhere in the integer part - where does not matter - and press any number, the valu will overflow. My plugin has no way of detecting this, because maskito already patched the value to max value before my plugin is called - any hints on how to fix this?

**Comment by nsbarsukov** [comment]
@mduft Hello!
I think it is better to use custom preprocessor instead of plugin for your task.
Learn more about preprocessors: https://maskito.dev/core-concepts/processors

Something like this:
```ts
import type { MaskitoPreprocessor } from '@maskito/core';
import {maskitoParseNumber} from '@maskito/kit';

const MAX = 99.99;
const DECIMAL_SEPARATOR = ',';

const myCustomPreprocessor: MaskitoPreprocessor = ({ elementState, data }) => {
  const { value, selection } = elementState;
  const [from, to] = selection;
  const newPossibleValue = value.slice(0, from) + data + value.slice(to);

  if (
    maskitoParseNumber(newPossibleValue, DECIMAL_SEPARATOR) > MAX &&
    !value.includes(DECIMAL_SEPARATOR)
  ) {
    return { elementState, data: DECIMAL_SEPARATOR + data };
  }

  return { elementState, data };
};
```

The full draft: https://stackblitz.com/edit/maskito-issue-1171

**Comment by nsbarsukov** [comment]
I'm closing this issue because we are not going to implement the such logic inside our built-in mask `Number`.
