### ISSUE TITLE
📚 - Using maskito with react-hook-form

### ISSUE THREAD

**Issue by ilterugur** [taiga-family/maskito#1189]
### Description

Hello, first of all, thanks for the library.
If I want to use use this library's react adapter with react-hook-form, what should I do? They both utilize ref props and we can give only one ref value to inputs.
Or if I want to use a regular ref object on an input and also use maskito on that, how can I pass my own ref value while using maskito's ref callback value?
Only way I found is giving maskito ref to a parent element and using elementPredicate option on useMaskito hook but it doesn't feel like it's the right way

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nextZed** [comment]
Hey there!
Since `ref` prop is a callback, you can do something like this:
```tsx
<YourAmazingInput
  ref={node => {
    maskitoRefCallback(node)
    myInputRef.current = node
  }}
/>
```

**Comment by mauriciocrecencio** [comment]
Hey guys, 

Is there some way to display default value with mask applied when using react-hook-form?

I'm trying to use Maskito with currency mask and react-hook-form for manage my form state, but initial state is the raw number, and the input is only numbers without $ or . ,

Example:
Initial State https://share.cleanshot.com/1p2gz9df
What should be https://share.cleanshot.com/vsTdwlgw

my input has initial value 12000 and it really display 12000, but only when start typing that mask are applied

**Comment by nsbarsukov** [comment]
> Hey guys,
> 
> Is there some way to display default value with mask applied when using react-hook-form?
> 
> I'm trying to use Maskito with currency mask and react-hook-form for manage my form state, but initial state is the raw number, and the input is only numbers without $ or . ,
> 
> Example: my input has initial value 12000 and it really display 12000, but only when start typing that mask are applied ![CleanShot 2024-04-23 at 20 58 25@2x](https://private-user-images.githubusercontent.com/65139661/325026210-2ee2f3d3-2100-4344-829b-542ea6ed4dbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDY1ODYsIm5iZiI6MTcxMzk0NjI4NiwicGF0aCI6Ii82NTEzOTY2MS8zMjUwMjYyMTAtMmVlMmYzZDMtMjEwMC00MzQ0LTgyOWItNTQyZWE2ZWQ0ZGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA4MTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYWM1NjI2Y2JjYTM2OGNhYmYzNTIzYjgzYzQ3YTE3NWMzMjk1YTA1YzczZjlhNzUzZDdkYmY1MDk3NmM5MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u57x-4C7Pw3AqwjRA9wbkedsmG29ReYKpqgr4HA_pUY)
> 
> ![CleanShot 2024-04-23 at 20 57 41@2x](https://private-user-images.githubusercontent.com/65139661/325026136-fa90945a-7b61-4b7e-a77a-b567677e8c0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDY1ODYsIm5iZiI6MTcxMzk0NjI4NiwicGF0aCI6Ii82NTEzOTY2MS8zMjUwMjYxMzYtZmE5MDk0NWEtN2I2MS00YjdlLWE3N2EtYjU2NzY3N2U4YzBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA4MTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNjk0NDFhYmRjZTdkYWFiZGQ5NWM5YTUxNjcxMDNmNTBkNzhiZjA4ZTA0MzRlYmJhOWZiMzI3YTVhOTE4YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H_1VfzHQ3gvaPdQfajb01Zm7F2l_lkIoIYu7AYxs9ks)

@mauriciocrecencio 

Use [maskitoInitialCalibrationPlugin](https://maskito.dev/core-concepts/plugins#initial-calibration) or [maskitoTransform](https://maskito.dev/core-concepts/transformer)

**Comment by wladpaiva** [comment]
Worked like a charm
```ts
const maskitoOptions: MaskitoOptions = {
  mask: /^\d+$/,
}

function Input({onChange, ...props}: React.ComponentProps<'input'>){
  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    event.currentTarget.value = maskitoTransform(
      event.currentTarget.value,
      maskitoOptions,
    )
  
    onChange?.(event)
  }
  
  return <input onChange={handleChange} {...props} />
}
```

**Comment by mykola-kolomoyets** [comment]
Faced the refs conflict issue, because the `useMaskito` hooks returns ref. And using `react-hook-form` means accepting the ref as well for acceptable form state management.

Here is the thing.

I have the form input field (shadcn-ui form layer is being used, but does not matter, taking into account that we use `react-hook-form`):

```jsx
<FormField
    control={form.control}
    name="purchasePrice"
    render={({ field }) => (
        <FormItem className="col-span-2">
            <div className="inline-flex items-center gap-1">
                <FormLabel>Purchase Price</FormLabel>
                <HelpTooltip Icon={CircleAlertIcon}>
                    // ...
                </HelpTooltip>
            </div>
            <FormControl>
                <CurrencyInput
                    placeholder="e.g $ 1.650"
                    value={field.value}
                    onChange={(event) => {
                        field.onChange(parseInt(event.target.value) || 0);
                    }}
                />
            </FormControl>
            <FormMessage />
        </FormItem>
    )}
/>
```

The `<CurrencyInput/>` components has such code:

```tsx
const CurrencyInput: React.ForwardRefRenderFunction<HTMLInputElement, React.ComponentPropsWithoutRef<'input'>> = (
    props,
    ref
) => {
    const currencyInputRef = useMaskito({
        options: CURRENCY_INPUT_MASKITO_OPTIONS,
    });

    return (
        <Input
            ref={
                // What should i pass here?
            }
            {...props}
        />
    );
};
```

- `merge-refs` library dod not work, because it is bad with accepring forward refs
```jsx
<Input ref={mergeRefs(ref, currencyInputRef) as React.Ref<React.ElementRef<'input'>>} {...props} />;
```

So it is impossible to use  the library in this way. WOuld it be possible to return not the ref as an option, but the props slice for this?

**Comment by waterplea** [comment]
Man, if only react had directives...

**Comment by nextZed** [comment]
@mykola-kolomoyets hey!
Did you try [solution](https://github.com/taiga-family/maskito/issues/1189#issuecomment-2058672706) that I provided above? Did it not work for some reason?
In your case it would look something like this:

```tsx
ref={node => {
  currencyInputRef(node)
  ref.current = node
}}
```

**Comment by leverage-analytics** [comment]
Hi, I'm trying to accomplish something similar but using the Controller implementation of Maskito, react-hook-form, and Material UI. 

I have the mask working when I am interacting with the field, but as soon as I tab away to the next field, the mask disappears, and the value returns to 0. It also does not appear when the form is first loaded. Any ideas?

Here is my implementation:

```
import { TextField } from "@mui/material";
import { Controller, RegisterOptions } from "react-hook-form";
import { MaskitoOptions } from "@maskito/core";
import { useMaskito } from "@maskito/react";

type InputTextProps = {
  name: string;
  label: string;
  control: any;
  mask: MaskitoOptions;
  options?: RegisterOptions;
  value?: string | number;
  required?: boolean;
  type?: "text"
};

export const FormMaskedInputText = ({
  name,
  label,
  control,
  mask,
  options,
  required,
}: InputTextProps): JSX.Element => {
  const maskitoRef = useMaskito({ options: mask });

  return (
    <Controller
      name={name}
      control={control}
      rules={options}
      render={({
        field: { onChange, onBlur, ref, value, name },
        fieldState: { error },
      }) => (
        <TextField
          helperText={error ? error.message : null}
          error={!!error}
          name={name}
          onChange={onChange}
          onBlur={onBlur}
          inputRef={(el: HTMLElement | null) => {
            maskitoRef(el);
            ref(el);
          }}
          label={label}
          required={required || true}
          value={value}
        />
      )}
    />
  );
};
```

And then rendering with:

```
import { SubmitHandler, useForm } from "react-hook-form";
import Box from "@mui/material/Box";
import Grid2 from "@mui/material/Grid2";
import { maskitoNumberOptionsGenerator } from "@maskito/kit";

import { FormMaskedInputText } from "./FormMaskedInputText";

const type Demo = {
  latitude: number;
  longitude: number;
}
  

export const DemoForm = ({
  data,
  onSubmit,
}: {
  data: Demo;
  onSubmit: SubmitHandler<Demo>;
}): JSX.Element => {
  const form = useForm<Demo>({
    defaultValues: data,
  });

  const latitudeMask = maskitoNumberOptionsGenerator({
    precision: 4,
    decimalZeroPadding: true,
    min: -90,
    max: 90,
  });

  const longitudeMask = maskitoNumberOptionsGenerator({
    precision: 4,
    decimalZeroPadding: true,
    min: -180,
    max: 180,
  });

  return (
    <Box component="form" onSubmit={form.handleSubmit(onSubmit)}>
      <Grid2 container>
        <Grid2>
          <FormMaskedInputText
            name="latitude"
            label="Latitude"
            control={form.control}
            mask={latitudeMask}
          />
        </Grid2>
        <Grid2>
          <FormMaskedInputText
            name="longitude"
            label="Longitude"
            control={form.control}
            mask={longitudeMask}
          />
        </Grid2>
        <input type="submit" />
      </Grid2>
    </Box>
  );
};

```

**Comment by leverage-analytics** [comment]
@nextZed Hey - did you have any ideas on the use case I shared? Thanks!

**Comment by nextZed** [comment]
@leverage-analytics could you please provide a stackblitz with example above?

**Comment by leverage-analytics** [comment]
@nextZed sure! [Here is a demo! ](https://stackblitz.com/edit/vitejs-vite-mimshw?file=src%2FDemoForm.tsx). Let me know if you have any questions

**Comment by somativa-victor-formisano** [comment]
I'm also facing this issue, did anyone made any progress?

**Comment by nextZed** [comment]
@leverage-analytics @somativa-victor-formisano 
When you use a controlled input, you need to pass `onInput` instead of `onChange`. More on the [docs](https://maskito.dev/frameworks/react) "Controlled masked input".
[Here's](https://stackblitz.com/edit/vitejs-vite-mimshw?file=src%2FFormMaskedInputText.tsx) working example.

Hope this helps!

**Comment by waterplea** [comment]
Should we add a big ass warning at the top of React page to use proper `onInput` in 2k24 if using the `onChange` is still so prominent in React community?

**Comment by leverage-analytics** [comment]
@nextZed that's great! Thank you so much for your help.

Just one quick follow-up question. Based on the discussion above, should the implementation we're discussing now mask the default form values? That's the only part that's still not working as desired for me.

**Comment by waterplea** [comment]
No, it only masks the value as user edits it. You can use `maskitoTransform` helper function or a `maskitoInitialCalibrationPlugin `:
https://maskito.dev/core-concepts/plugins#initial-calibration

The reason we have it like that is imagine the following scenario:
A user is applying for a loan and enters a date within the limits of the form. Then they save it as a draft and open it in a few days. The limits would be different and the date user entered might fall out of them. If we automatically change it to the first available date (which min/max params do in date mask as you type it) — we would have altered the users input without them noticing. That could be very bad if the data is sensitive. So by default we do not change any data unless triggered by user input, but it's easy to enable by adding the plugin provided out of the box.
