### ISSUE TITLE
📚 - Update documentation about supported types of `<input />`

### ISSUE THREAD

**Issue by Semanual** [taiga-family/maskito#1190]
### Which package(s) are the source of the bug?

@maskito/core

### Playground Link

https://stackblitz.com/edit/5cd2ez?file=index.ts

### Description

**Steps to reproduce:**
Just write any number at the input box

I understand that in #1121 you said it is impossible to support `<input type="number"/>`, and okay, I get it, it is not supported, we shouldn't use it in first place. But this error message (`An attempt was made to use an object that is not, or is no longer, usable`) does not help at all, and things actually go wrong inside the code, without any hint that `type="number"` is the root problem. Could you please update this to an error message like, `Type "number" in inputs is not supported, please use type "text" instead`? (I am not sure if this should be a feature request, but it is caused by a bug, so I'm filling a bug report)

### Maskito version

2.2.0

### Which browsers have you used?

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
```diff
- - You can use it with `HTMLInputElement` or `HTMLTextAreaElement` or even with `[contenteditable]` element.
+ - You can use it with `<input type="text" />` or `<textarea />` or even with `[contenteditable]` element.
```

**Comment by waterplea** [comment]
Probably a good idea to explicitly state it does not work with other types and maybe even state a reason or link to your investigation.
