### ISSUE TITLE
🚀 - `strict` and `non-strict` modes for `Date`, `DateRange`, `DateTime`

### ISSUE THREAD

**Issue by KrollikRoddzer** [taiga-family/maskito#1217]
### Which package(s) are relevant/related to the feature request?

@maskito/kit

### Description

It is proposed to introduce new boolean parameter `strict`.
This new parameter decides if Maskito can calibrate not currently active date segment for invalid date.
```ts
import {maskitoDateOptionsGenerator} from '@maskito/kit';

const maskitoOptions = maskitoDateOptionsGenerator({
    mode: 'yyyy/mm/dd',
    strict: true
});
```
**Default value**: `true` (add `TODO`-comment to change it to `false` in future major release). 

### Strict:
This behavior is already implemented in our mask.
In strict mode, if a user tries to enter a non-valid date, the mask will either prevent the user from entering such a date, or if it is possible to turn it into a valid date, it will change it to a valid date. Textfield's value NEVER contains invalid date value.

> **Enabled strict can change even not currently active date segment!**
>
> For example, user overwrites month segment (active date segment – month) and new typed month does not contains the such day segment (i.e. 31st day). Day segment is calibrated automatically.

_Hint_: use native `Date` for automatic value calibration.

#### Examples:

_Date mask_: `mm/dd/yyyyy`

- `02.29.202|` ⇒ Type 5 ⇒ `03.01.2025|`
- `04|` ⇒ Type 4 ⇒ `04.04|`
- `04.31.2007` ⇒ `05.01.2007`
- `02.31.2025` ⇒ `03.03.2025`

### Non-strict:

In non-strict mode, textfield sometimes can contains not-valid date (i.e. 31st day for month with only 30 days).

> **Non-strict can NOT change not currently active date segment!**
>
> For example, user overwrites month segment (active date segment – month) and new typed month does not contains the such day segment (i.e. 31st day). Day segment is NOT calibrated automatically.

`Day: max 31, min 1`
`Year: max 9999, min 1`
`Month: max 12, min 1`

Checking for non-valid dates in this case will fall on the developers.
For example, developer can use visual way to represent that textfield contains invalid date (i.e. angular form validators).
See good example of non-strict date mask: https://mui.com/x/react-date-pickers/adapters-locale/#with-luxon

#### Examples:

_Date mask_: 'mm/dd/yyyyy'

1. `02.29.2025` ⇒ `02.29.2025` 
2. `04.31.2007` ⇒ `04.31.2007`

**Comment by nsbarsukov** [comment]
Closing this issue until it becomes more relevant for us
