### ISSUE TITLE
Vue with js support 🚀 - 

### ISSUE THREAD

**Issue by Iterationplus-dev** [taiga-family/maskito#1222]
### Which package(s) are relevant/related to the feature request?

@maskito/core, @maskito/vue

### Description

Support for vue using js

**Comment by nsbarsukov** [comment]
`@maskito/vue` supports both JS and TS projects.

**Proofs:**
* https://stackblitz.com/edit/vue-js-only-with-maskito?file=src%2FApp.vue
* https://stackblitz.com/edit/maskito-vue-starter
