### ISSUE TITLE
🐞 - `Number` does not support float `min`-parameter (0 < x < 1)

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/maskito#1225]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://maskito.dev/kit/number/API?min=0.2&precision=2

### Description

**Case 1:**
1. Open https://maskito.dev/kit/number/API?min=5.1&precision=2
2. Enter `5.1` (min value)
3. Type `Backspace`

Decimal digit is erased and new digit can be typed ✅ 

___

**Case 2:**
1. Open https://maskito.dev/kit/number/API?min=0.1&precision=2
2. Enter `0.1` (min value)
3. Type `Backspace`

It is impossible to erase decimal part ❌

https://github.com/taiga-family/maskito/assets/35179038/04baaa2c-e366-4650-9a50-0c812f74df68

### Maskito version

2.3.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by selected-pixel-jameson** [comment]
I'm having the same issue with this configuration.

```
export const CURRENCY_MASK: MaskitoOptions = maskitoNumberOptionsGenerator({
  decimalZeroPadding: true,
  precision: 2,
  decimalSeparator: '.',
  thousandSeparator: ',',
  min: 0.01,
  max: 100000000,
  prefix: '$',
});
```

**Comment by nsbarsukov** [comment]
@selected-pixel-jameson I'll fix it soon (on next week, probably).

If you need it ASAP – feel free to open your PR with contribution.

**Comment by selected-pixel-jameson** [comment]
@nsbarsukov Thank you, much appreciated.
