### ISSUE TITLE
🐞 - `DateRange` should accept single character date segment during paste when date separated by '-' sign

### ISSUE THREAD

**Issue by stanislav-osipov** [taiga-family/maskito#1256]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://maskito.dev/kit/date-range/API

### Description

Original issue https://github.com/taiga-family/maskito/issues/593 fixes the problem for dates formatted with dots like `11.9.2022`.
The bug still can be reproduced with dates like `11-9-2022` or `7-10-2020` for `DateRange` only. Works fine for `Date` and `DateTime`.

Steps to reproduce
https://maskito.dev/kit/date-range/API?mode=dd%2Fmm%2Fyyyy

Paste 11-9-2022
✅ Expected behaviour:
Textfield contains 11.09.2022

❌ Actual behaviour:
Textfield contains 11.09.022

### Maskito version

2.3.2

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by Suldenkov** [comment]
Hi! I`ll take it

**Comment by nsbarsukov** [comment]
@Suldenkov Hello!
Any updates ?

**Comment by Suldenkov** [comment]
> @Suldenkov Hello! Any updates ?

Hi! I found the cause of the error, but I don't know how to fix it yet. Because the original string uses a split by spaces, it's not clear how to distinguish them
