### ISSUE TITLE
🐞 - `Time` with `[step]` has unexpected cursor jump to the next segment on `ArrowUp`/ `ArrowDown`

### ISSUE THREAD

**Issue by demensky** [taiga-family/maskito#1303]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://maskito.dev/kit/time#step

### Description

If the time is not entered completely and the cursor is at the end of the segment (before the colon), then when you try to change the value by pressing the arrow keys, the cursor jumps to the beginning of the next segment.

https://github.com/taiga-family/maskito/assets/10235949/b2c6454d-d9fb-4d43-beae-ec5fb7f33dbc

### Maskito version

2.4.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by reverie3** [comment]
@nsbarsukov, could you assign the issue to me, please?
