### ISSUE TITLE
🐞 - `Date` with partially completed value has autofill problems in Firefox

### ISSUE THREAD

**Issue by kornblum** [taiga-family/maskito#1322]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/sw2whh

### Description

In Firefox there is a problem that the auto-fill function does not work as expected. You can also reproduce the problem with the link I provided. If the field is empty and you accept the browser suggestion, then everything looks correct. However, if you enter a value such as "1" beforehand and then select the browser suggestion, the date is displayed incorrectly (see screenshots). 
However, the problem does not occur in all browsers. For example, it works correctly in Chrome.

Auto-fill suggestion:
<img width="483" alt="Bildschirmfoto 2024-06-19 um 10 21 35" src="https://github.com/taiga-family/maskito/assets/3379004/0b656ac2-efb3-4841-9670-b42237a6019f">

Result:
<img width="457" alt="Bildschirmfoto 2024-06-19 um 10 21 43" src="https://github.com/taiga-family/maskito/assets/3379004/a25b2f39-a7e2-41b3-a68f-60788dbb27d0">

### Maskito version

2.4.0

### Which browsers have you used?

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
@kornblum Unfortunately, I cannot open your url (it returns 403 error).

Create reproduction using Stackblitz Starter, please:
https://maskito.dev/stackblitz

**Comment by kornblum** [comment]
@nsbarsukov sure. https://stackblitz.com/edit/sw2whh

I recommend entering a date first and then submitting the form. The browser should then suggest the value the next time you enter it.
