### ISSUE TITLE
🐞 - maskitoStringifyTime convert to wrong time

### ISSUE THREAD

**Issue by gleysonabreu** [taiga-family/maskito#1399]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/79evv4?file=index.ts (see console.log)

### Description

When you convert from "parse time" to "stringify time" some combinations are put wrong, for example:
03:02:00 generates 10920000
But when you try to convert to string it returns:
30:20:00 instead of 03:02:00.

I believe the problem maybe is in the padTimeSegments, which should put "0" at the beginning and not at the end, but messing with this breaks all parse-time.ts tests.

### Maskito version

2.5.0 and 3.0.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
@demensky Hello!

Do you want to fix this issue ?

**Comment by demensky** [comment]
Ok, @nsbarsukov, I'll do it soon.
