### ISSUE TITLE
Provide "no-module" version

### ISSUE THREAD

**Issue by movedoa** [taiga-family/maskito#1404]
### Description

Please provide a version that doesn't require the use of modules. 
A "classic" version that can be loaded in the script tag with a global on the window object (or global const) would make using your lib a lot easier when modules are not an option.

**Comment by waterplea** [comment]
@movedoa what are the cases where modules are not an option?

**Comment by movedoa** [comment]
> Hello!
> 
> You can use any CDN you wish. For example: https://www.jsdelivr.com/package/npm/@maskito/core
> 
> See this StackBlitz: https://stackblitz.com/edit/maskito-simple

That was my first idea and it works with just the core package put i couldn't make maskito kit work this way.
This doesnt work:

```
const { Maskito } = await import(
  'https://cdn.jsdelivr.net/npm/@maskito/core@3.0.0/index.esm.min.js'
);

const { MaskitoKit } = await import(
  'https://cdn.jsdelivr.net/npm/@maskito/kit@3.0.0/index.esm.min.js'
);

const input = document.querySelector('input');
const options = {
  mask: [/\d/, /\d/, /\d/],
};

new Maskito(input, options);
```

> @movedoa what are the cases where modules are not an option?

My app started before modules where a thing, its a pretty big code base that makes heavy use of typescript namespaces.
I tried migrating in the past and gave up after a while because modules dont support circle references, my cache busting stategy didn't work anymore and some other suff that would require major rewrites of the code base.
While i understand that I probably have to migrate some day, currently I see no real benefit for a lot of work.
Its probably a bit of a niche use case but i'm probably not alone with a code base where modules create more problems than they solve.

**Comment by waterplea** [comment]
Or alternatively do not destructure it:
```ts
const MaskitoKit = await import(
  'https://cdn.jsdelivr.net/npm/@maskito/kit@3.0.0/index.esm.min.js'
);

MaskitoKit.maskitoParseNumber(...);
```

**Comment by movedoa** [comment]
Ah right, i will give it a go.
Thx for the fast help.

**Comment by movedoa** [comment]
Sorry for the noise, i'm probably just missing something obvious here but the following code also doesn't work in stackblitz.
When i import MakitoKit, the mask doesnt work anymore, when i comment out the second import the mask works

const { Maskito } = await import(
  'https://cdn.jsdelivr.net/npm/@maskito/core@3.0.0/index.esm.min.js'
);
const MaskitoKit = await import(
  'https://cdn.jsdelivr.net/npm/@maskito/kit@3.0.0/index.esm.min.js'
);

const input = document.querySelector('input');
const options = {
  mask: [/\d/, /\d/, /\d/],
};

new Maskito(input, options);

**Comment by nsbarsukov** [comment]
@movedoa
You can use power of [<script type="importmap">](https://developer.mozilla.org/docs/Web/HTML/Element/script/type/importmap).

See this StackBlitz example:
https://stackblitz.com/edit/maskito-core-kit-via-jsdelivr

___

Alternatively, you can choose another CDN source.
For example, you can [Skypack](https://www.skypack.dev) even without `importmap`.

See another StackBlitz example:
https://stackblitz.com/edit/maskito-core-kit-via-skypack
