### ISSUE TITLE
🚀 - add plugins option to maskitoPhoneOptionsGenerator

### ISSUE THREAD

**Issue by 1001v** [taiga-family/maskito#1437]
### Which package(s) are relevant/related to the feature request?

@maskito/phone

### Description

Hello. I would like to have the plugins field for maskitoPhoneOptionsGenerator options for passing extra plugins.
For instance, I need maskitoInitialCalibrationPlugin alongside with maskitoPhoneOptionsGenerator.  Of course I could just push a plugin to the MaskitoOptions object, but it's not very convinient since MaskitoOptions['plugins'] is a readonly array.
Thanks.

**Comment by nsbarsukov** [comment]
@1001v Hello!

Adding additional plugins to any built-in mask is easy and does not required adding of additional properties.

```ts
const phoneOptions = maskitoPhoneOptionsGenerator({
  metadata,
  countryIsoCode: 'US',
});

const upgradedPhoneOptions: MaskitoOptions = {
  ...phoneOptions,
  plugins: [
    ...phoneOptions.plugins,
    maskitoInitialCalibrationPlugin()
  ],
};
```

See another example:
* https://maskito.dev/addons/phone#focus-blur

**Comment by 1001v** [comment]
@nsbarsukov, Hello. Thanks for pointing this out.
