### ISSUE TITLE
🐞 - Can't understand string and construction as "\d{4}". Only "\d{4,4}"

### ISSUE THREAD

**Issue by NataliyaTar** [taiga-family/maskito#1655]
### Which package(s) are the source of the bug?

@maskito/angular

### Playground Link

https://stackblitz.com/edit/59y1pa?file=index.ts

### Description

In my case, I should use mask with string of mask which come from back. It's mask '\\d{2}:\\d{2}:\\d{6,7}:\\d+|0:0:0:\\d+'.
First, new RegExp() of this mask doesn't work. Mask should has ^ and $ (but i can't have it from back)
Second, I founded "\d{4}" doesn't work. It works only with 2 params, like "\d{4,4}"
In Playground I show some different masks

The second problem is more critical for me than first

### Maskito version

3.0.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
Hello!

**The first case**.
Yep, mask reg exp should be started/ended with `^` and `$`. 
Maskito does not transform any passed reg exp. It will be too much for the tiny library.

Just use [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) constructor to add it:
```ts
const yourRegExpStringFromBackend = '...';
const finalRegExp = new RegExp(`^` + yourRegExpStringFromBackend + '$');
```
___

**The second case.** 
Read this section from the documentation
https://maskito.dev/core-concepts/mask-expression
<img width="796" alt="mask-expression" src="https://github.com/user-attachments/assets/5c0a770a-588c-47e2-afcf-7c91c93f6c37">
