### ISSUE TITLE
🐞 - `Number` + postfix (with leading space) adds unnecessary spaces on paste of decimal number

### ISSUE THREAD

**Issue by mariorudloff** [taiga-family/maskito#1820]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/bsm8fn?file=index.ts&hideExplorer=1

### Description

When you use these settings to configure Maskito:

```typescript
const maskitoOptions: MaskitoOptions = maskitoNumberOptionsGenerator({
  postfix: ' EUR',
  thousandSeparator: '.',
  decimalSeparator: ',',
  precision: 2,
  decimalZeroPadding: true,
  minusSign: '-',
});
```
Then its possible to paste extra spaces into the field between the postfix and the number.
This only happens when the field is completely empty.

# Steps:
- Load Page and see empty maskito input
  ![Image](https://github.com/user-attachments/assets/ada4dab1-e23f-427f-8742-a482e86d6241)
- paste `1234,12   ` into the input (with trailing spaces)

**Expected:**
![Image](https://github.com/user-attachments/assets/e9892415-f158-41f9-9a41-8bc320cc6e82)

**Saw:**
![Image](https://github.com/user-attachments/assets/0beaf475-8b3d-40e6-ac06-b51316cda80e)

### Maskito version

3.2.0

### Which browsers have you used?

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [x] Edge

### Which operating systems have you used?

- [ ] macOS
- [x] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
### Prerequisites
```ts
const maskitoOptions: MaskitoOptions = maskitoNumberOptionsGenerator({
  postfix: ' EUR', // with leading space!
  precision: 2,
});
```

### Test cases
- Insert number with integer part only (with trailing spaces) - no bug ✅ 
  ```
  12        
  ```

- Insert number with decimal part  (with trailing spaces) - bug ❌
  ```
  1.2       
  ```

**Comment by nsbarsukov** [comment]
For contributors – dont forget to write some Cypress tests.

Example:
https://github.com/taiga-family/maskito/blob/ea490b071d0334c680519b841686935b030dbf82/projects/demo-integrations/src/tests/kit/number/number-thousand-separator.cy.ts#L160-L166

**Comment by AndreiBelokopytov** [comment]
Hey! Can I get this one?
