### ISSUE TITLE
🐞 - Documentation page `Browser Support` contains outdated information

### ISSUE THREAD

**Issue by kowalczyk-mateusz** [taiga-family/maskito#1872]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://maskito.dev/browser-support

### Description

Hi, i have an error on olders browser that are not supported by maskito. is it possible to add somehow polyfill? i tried to use import 'core-js/actual/string/replace-all'; but this didn't fixed the issue.
error i got is
```
TypeError: str.replaceAll is not a function at escapeRegExp
./node_modules/@maskito/kit/index.esm.js
```
If i downgrade maskito to 1.8.* it works fine. We have some users that uses older browsers versions, and i would like to add polyfill for them somehow. Is it possible? Thanks :)

### Maskito version

3.2.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
@kowalczyk-mateusz Hello!

> i tried to use import 'core-js/actual/string/replace-all'; but this didn't fixed the issue.

Probably, you did something wrong because it should actually works.
Explore this StackBlitz: https://stackblitz.com/edit/maskito-polyfill-legacy-browsers
(I've tested this sandbox in legacy Chrome Chrome – it works with `import 'core-js/actual/string/replace-all'` and it throws error without it).

**Comment by nsbarsukov** [comment]
As for documentation page [Browser Support](https://maskito.dev/browser-support).
At present time, it contains not up-to-date information about minimum required browsers – it should be fixed to solve this issue.
