### ISSUE TITLE
🚀 - Get/set history

### ISSUE THREAD

**Issue by demensky** [taiga-family/maskito#234]
### Which package(s) are relevant/related to the feature request?

@maskito/core

### Description

You need the ability to get and set history. This will allow you to save it and reuse it in the future.

For example:

Store in `history.state` so that if the user refreshes the page or leaves the page and comes back to it again, he will still have the opportunity to undo. An explicit example is a search box.

**Comment by waterplea** [comment]
I wonder if it's really necessary 🤔 I don't think people expect Cmd+Z to work after page refresh.

**Comment by waterplea** [comment]
We decided not to do this at this time. If somebody wants it, feel free to post a message here so we can see if there's a practical demand for such a feature.
