### ISSUE TITLE
🚀 - Add RTL support for `maskitoPrefixPostprocessorGenerator` / `maskitoPostfixPostprocessorGenerator`

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/maskito#258]
### Which package(s) are relevant/related to the feature request?

@maskito/kit

### Description

Generators will get new second **optional** argument – `direction` (`ltr` by default).

**Example:**
```ts
postprocessor: maskitoPipe(
        maskitoPrefixPostprocessorGenerator('$', 'rtl'),
        maskitoPostfixPostprocessorGenerator('.00', 'rtl'),
    ),
```

**Comment by waterplea** [comment]
I think we should try and get in touch with somebody from Arabic countries to see if it makes sense, because it depends on the actual characters. I'll try to reach out to somebody after vacation.
