### ISSUE TITLE
🐞 - Character duplications on Android Pixel devices (mobile chrome)

### ISSUE THREAD

**Issue by demkalkov** [taiga-family/maskito#418]
### Which package(s) are the source of the bug?

@maskito/core

### Playground Link

https://stackblitz.com/edit/5kg3w1

### Description

When trying to add first digit from a number, it is doubled and the caret is placed before them. So when a 'C 1' is entered a user actually sees 'C 11'. 
Having no spaces between letters and digits doesn't fix the problem.

Could be able to reproduce on Pixel devices (6-7) starting from Chrome v114.0.5735.130

Same Chrome version on Samsung device has no issue

### Maskito version

1.2.1 - 1.4.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [X] Android

**Comment by nsbarsukov** [comment]
Android Pixel devices (+ some other androids) any typing of letters is mistakenly interpreted as `insertCompositionText` input type.

In #467 support of IME was added.
It means that this bug will be also solved (now Android Pixel devices will not duplicate characters).
**BUT!**
Any masking operations for these androids will happen ONLY AFTER `compositionend` event (not immediately).
