### ISSUE TITLE
🚀 - Add `DateTimeRange` mask

### ISSUE THREAD

**Issue by Sergey-Gerasimov** [taiga-family/maskito#443]
### Which package(s) are relevant/related to the feature request?

@maskito/kit

### Description

Maskito already has DateRange and DateTime masks.
Seems logical to add DateTimeRange mask generator.

# Example
```
01.01.2000, 20:00 – 10.01.2000, 23:59
```

**Comment by nsbarsukov** [comment]
We had many discussions with our UX/UI colleagues about this feature. 
We conclude that the such mask is too complex for users and it produces the bad UX. The such masked textfield should be splitted into at least 2 separate fields.

Our final decision – not implement this feature request.
