### ISSUE TITLE
🚀 - Make @maskito/phone avaiable on npm

### ISSUE THREAD

**Issue by rodrigo-bejar** [taiga-family/maskito#491]
### Which package(s) are relevant/related to the feature request?

Don't known / other

### Description

@maskito/phone is not published on npm

Although the documentation says that I can install with `npm install @maskito/phone` the command result is:
npm ERR! 404  '@maskito/phone@*' is not in this registry.

**Comment by nsbarsukov** [comment]
@rodrigo-bejar Hello!

New `@maskito/phone` library is "in progress" status.
When we finalize the final public API, we will publish it to npm.

Keep track of the following issue:
* https://github.com/taiga-family/maskito/issues/323

Also, you can subscribe to release notes to be notified of upcoming release.
