### ISSUE TITLE
🐞 - Was phone package removed? Why?

### ISSUE THREAD

**Issue by allanmcarvalho** [taiga-family/maskito#513]
### Which package(s) are the source of the bug?

Don't known / other

### Playground Link

https://www.npmjs.com/package/@maskito/phone

### Description

I am trying install maskito phone package using as asked by documentation `npm install @maskito/phone`. But appears that the package don't exists.

On npm site it don't exists too.

### Maskito version

1.6

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [X] Linux
- [X] iOS
- [X] Android

**Comment by nsbarsukov** [comment]
This new package will be published in 5-10 minutes 😄 

It will be the first its release
