### ISSUE TITLE
🐞 - Non standard negative sign

### ISSUE THREAD

**Issue by IRadics** [taiga-family/maskito#550]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/5lltdb?file=index.ts

### Description

Maybe it is by design, but I have encountered an issue when I could not parse negative number - generated by the maskitoNumberOptionsGenerator and took some time to figure out. The negative sign the mask uses is "non-standard", as in not the same as you would enter with a keyboard.

I am using maskito with Angular. We parse the value to a number before sending it to the server. The thousand separator is expected and we handled it well, however the special minus sign was not expected and solved it with a postprocessor function to replace it.

In the playground link you can see the implementation - I simply replace it with the  "standard" minus sign. 

My suggestion would be to add an option to maskitoNumberOptionsGenerator to use the standard negative sign. OR maybe alternatively an option to provide a function to emit a value, but keep the input formatted - although that may be problematic and/or very "workaround-ish"

### Maskito version

1.7.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
There's a `maskitoParseNumber` utility function in `@maskito/kit` package, so you do not need your own parsing implementation. I believe it solves the issue?

Regarding the symbol choice, it is not what you would enter with the keyboard, that's correct, but it is the proper symbol called `&minus;` to be used in case of formatted numbers, while the keyboard symbol is `&dash;`/`&hyphen;` which should be used mid-word. I know it might cause some confusion, but since you would either use it "as is" or parse the string into number, for which we supply the utility function, I believe it should be ok.

**Comment by IRadics** [comment]
> There's a `maskitoParseNumber` utility function in `@maskito/kit` package, so you do not need your own parsing implementation. I believe it solves the issue?
> 
> Regarding the symbol choice, it is not what you would enter with the keyboard, that's correct, but it is the proper symbol called `&minus;` to be used in case of formatted numbers, while the keyboard symbol is `&dash;`/`&hyphen;` which should be used mid-word. I know it might cause some confusion, but since you would either use it "as is" or parse the string into number, for which we supply the utility function, I believe it should be ok.

True, I missed that function. I plugged it in an already existing project, which used another package textmask before (which is not compatible with newer Angular versions, so I needed to replace it), that is why I kind of missed the whole thing as the parsing happened on a different end. Either way, I thing an option to override the actual character would be nice (also as an indication that developers should pay attention to it). For us, it is now working correctly- although I will check out the `maskitoParseNumber `, probably would make a more elegant solution compared to what I did.

**Comment by nsbarsukov** [comment]
**Solution**: use  `maskitoParseNumber`.

```ts
import {maskitoParseNumber} from '@maskito/kit';

maskitoParseNumber(
  '−123 456', // document.querySelector('input').value
  ',', // decimal separator (dot is default)
); // -123456
```

Learn more: https://maskito.dev/kit/number
