### ISSUE TITLE
🐞 - maskitoWithPlaceholder with focusedOnly false not visible

### ISSUE THREAD

**Issue by ambrodrigues** [taiga-family/maskito#609]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/ifye36?file=index.ts,mask.ts

### Description

when using the maskitoWithPlaceholder method with the parameter focusedOnly = false the placeholder is not visible. I believe that the placeholder should always appear with this false parameter

### Maskito version

1.8.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
@ambrodrigues Hello!

Just initialize `input`-element with right value.
For initially "empty"-date use the following lines:

```html
<input value="dd/mm/yyyy" />
```

And then everything should works fine.
See this stackblitz: https://stackblitz.com/edit/maskito-date-placeholder-always?file=mask.ts,index.html

___

**Why so ? Why we can't just do it by ourself inside mask?**
We need to provide flexibility about this case: some developer want textfield to be initially filled with placeholder, but others don't.
The current behaviour allows to choose.

In **Maskito** 2.0 we want to change this behaviour a little bit:
https://github.com/taiga-family/maskito/issues/604
Initial calibrations will be optional and user can enable it by `maskitoInitialCalibrationPlugin`.

**Comment by nsbarsukov** [comment]
I will close this issue because further improvements of `maskitoWithPlaceholder ` will be done in this issue:

* https://github.com/taiga-family/maskito/issues/604#issuecomment-1770226977
