### ISSUE TITLE
📚 - Improve dark mode in documentation pages about `React` & `Vue`

### ISSUE THREAD

**Issue by mrJolla** [taiga-family/maskito#643]
### What is the affected URL?

https://maskito.dev/frameworks/react

### Description

Native inputs always have light background, you cannot see the text
<img width="253" alt="Снимок экрана 2023-11-01 в 23 25 02" src="https://github.com/taiga-family/maskito/assets/46539278/42ed62a3-022a-4a61-a598-16b4faf64be1">

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I suppose we just need to apply our CSS vars to style it:
```css
    background: transparent;
    border: 1px solid var(--tui-base-03);
    color: var(--tui-text-01);
```
@mrJolla would you be interested in making a PR for it?

**Comment by demensky** [comment]
@waterplea
I think `color-scheme: light dark` will solve this problem.

**Comment by waterplea** [comment]
> @waterplea
> I think `color-scheme: light dark` will solve this problem.

Would you be interested in making a PR?
