### ISSUE TITLE
Mask US zipcode with optional dash and 4 digits

### ISSUE THREAD

**Issue by mdodge-ecgrow** [taiga-family/maskito#676]
I just found this masking library after trying several others and not happy with the options in the other ones.  This one definitely seems the most feature packed.  I am trying to figure out how to mask a US zip code with optional dash followed by 4 digits.

This is what I currently have:
```
export const zipCodeMask = {
	...maskitoWithPlaceholder('_____'),
	mask: [/\d/, /\d/, /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/]
} as MaskitoOptions;
```
I guess my main issue is that after you type a 5th digit, it auto pops up that dash.  I would want it to add the dash when the 6th digit is typed only.  And also, I would like to switch the placeholder to '_____-____' after the 6th digit is typed.
Right now, even when I blur the input field, it looks like this:
![image](https://github.com/taiga-family/maskito/assets/57459547/76756b62-624a-4545-bf7a-ec405b6d5506)

**Comment by nsbarsukov** [comment]
@mdodge-ecgrow 

Hi!

I am not sure that I fully understand your issue.
Probably, you need **dynamic mask expression**.
Learn more: https://maskito.dev/core-concepts/mask-expression
You can do something like this: https://stackblitz.com/edit/zip-dynamic-mask-expression

___

As for `maskitoWithPlaceholder`.
Unfortunately, it does not support dynamic change of its argument.
I think that you can contribute to our repository and change signature of `maskitoWithPlaceholder`.

from 
```ts
export function maskitoWithPlaceholder(
    placeholder: string,
    focusedOnly = false,
)
```

to

```ts
export function maskitoWithPlaceholder(
    placeholder: string | (elementState: MaskitoElementState) => string,
    focusedOnly = false,
)
```

**Comment by mdodge-ecgrow** [comment]
Thank you.  Sorry if I was unclear.  I want to be able to enter 5 numbers as one option.  Most zip codes are that way.  However sometimes, to be more accurrate, they add 4 more digits with a dash in between.  So I want it to correctly accept 5 consecutive numbers, which it does fine.  Then I want it to optionally allow after the 5 numbers, a dash followed by 4 more digits.  So the two valid options would look like `12345` or `12345-6789`.  But I want that hyphen to auto show when the 6th number is typed, not after the 5th number is typed.  I tried to modify your example, but now I can't type more than 5 digits.  
https://stackblitz.com/edit/zip-dynamic-mask-expression-zpq5gn?file=index.ts

**Comment by mdodge-ecgrow** [comment]
And second related question is the placeholder.  I want it to show 5 underscores `_ _ _ _ _` when at first when the field is focused.  When they type the 6th number, i want it to now show `12345-6_ _ _`.  Does that make sense?

**Comment by nsbarsukov** [comment]
> And second related question is the placeholder. I want it to show 5 underscores `_ _ _ _ _` when at first when the field is focused. When they type the 6th number, i want it to now show `12345-6_ _ _`. Does that make sense?

As for `Placeholder`.
See my previous answer https://github.com/taiga-family/maskito/issues/676#issuecomment-1816051108
