### ISSUE TITLE
Why the last part of any phone number is joined with a - ?

### ISSUE THREAD

**Issue by alexdabast** [taiga-family/maskito#680]
Hi,

On this line
https://github.com/taiga-family/maskito/blame/74654ef3e3807e462be2f0db1469d0ea9a4079ca/projects/phone/src/lib/masks/phone/utils/get-phone-template.ts#L10
A join with '-' is made for the last part of any phone number. This is wrong and breaks any validation done by libphonenumber-js library when using parsePhoneNumberFromString.
I assume it is maybe a standard format number in russia or other countries but many EU countries do not have any characters in their national phone number

**Comment by waterplea** [comment]
Original `libphonenumber` by Google does use dashes though. Since our own standards suggest using dash and removal of it was a decision of `libphonenumber-js` author we reintroduced them. I suppose we can make this configurable.

**Comment by alexdabast** [comment]
I see, thank you for clarification how ever as the phone addon is based on libphonenumber-js I think you should align the format.
