### ISSUE TITLE
🐞 - `Placeholder` and textfield value cannot have the same characters

### ISSUE THREAD

**Issue by mdeforestbrown** [taiga-family/maskito#724]
### Which package(s) are the source of the bug?

@maskito/core, @maskito/kit, @maskito/react

### Playground Link

https://aetw2m.stackblitz.io

### Description

Example maskito configuration below. 

```
const DATE_MASK: MaskitoOptions = {
  ...maskitoWithPlaceholder("DD/MMM/YYYY"),
  mask: [
    /\d/,
    /\d/,
    "/",
    /[a-zA-Z]/i,
    /[a-zA-Z]/i,
    /[a-zA-Z]/i,
    "/",
    /\d/,
    /\d/,
    /\d/,
    /\d/,
  ],
};
```

In the example video below I'm attempting to type "Mar" or "May" in the month input but it is blocked.

https://github.com/taiga-family/maskito/assets/43621400/831dd30a-47dd-4075-a775-dca4af48dd89

### Maskito version

1.4.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nicopir** [comment]
Hello !

I've also noticed the issue when integrating this library into my project. It's impossible to enter the value of the next placeholder character, which makes the placeholder unusable if it's supposed to serve as an example of the expected format.

Will this bug be addressed anytime soon?

Thanks

**Comment by nsbarsukov** [comment]
@nicopir Hello!

The bugfix is released.
