### ISSUE TITLE
🚀 - Fancy currency input

### ISSUE THREAD

**Issue by Billzabob** [taiga-family/maskito#743]
### Description

Would it be possible to achieve something like the video below with this library?
It would be awesome if it was built into `maskitoNumberOptionsGenerator` as an option.

I tried getting it to work by messing around with preprocessors, postprocessors, and dynamic masks and was unsuccessful.

By the way this is the nicest masking library I've found so far, awesome work!! 🎉 

https://github.com/taiga-family/maskito/assets/3711832/dadf3601-2b4d-4bcd-b868-26cc4f732f30

**Comment by Billzabob** [comment]
Actually, I think I finally got this working with this:
```javascript
const moneyMask: MaskitoOptions = {
  mask: /^[0-9,.]*$/,
  postprocessors: [
    ({ value, selection }) => {
      const newValue = format(value);
      const [from, to] = selection;
      const extraCharCount = newValue.length - value.length;
      return {
        value: newValue,
        selection: [from + extraCharCount, to + extraCharCount],
      };
    },
  ],
};

const toNumber = (value: string): number => parseInt(value.replace(/\D/g, '')) / 100;
const fromNumber = (value: number): string => value.toFixed(2).replace(/\d(?=(\d{3})+\.)/g, '$&,');
const format = (value: string): string => fromNumber(toNumber(value));
```

**Comment by nsbarsukov** [comment]
Close this issue because working solutions can be easily configured (see https://github.com/taiga-family/maskito/issues/743#issuecomment-1847903487 above).

I think that adding this behaviour for built-in `Number` is too much and can cause many other bugs.

**Comment by Chitzi** [comment]
Some problems on this solution


https://github.com/taiga-family/maskito/assets/14255015/96521b5c-22db-4d10-9ccb-0d182eb9ea12
