### ISSUE TITLE
🐞 - Plugins, that set value into input don't call onInput in React

### ISSUE THREAD

**Issue by aktanoff** [taiga-family/maskito#804]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/stackblitz-starters-chezz9?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx&title=React%20Starter

### Description

Leading zero plugin and others doesn't work on blur, it sets the value, but this change don't fire in React's syntheticevent handler `onInput`, and value in state and value in input become different.

By little research i found out that it's because `bubbles` sets to false by default, and react don't handle events like this.
I've made a little example of how this works without maskito (just with react and dispatchEvent)
https://codesandbox.io/p/sandbox/pensive-shamir?file=%2Fsrc%2FApp.tsx%3A47%2C40
You can click here on buttons and it will dispatch events with and without bubbles parameter.

And example of how this works with maskito
https://stackblitz.com/edit/stackblitz-starters-chezz9?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx&title=React%20Starter
1. Open link
2. Type '000123'
3. Blur input somehow

**Expected:**
Value above input is '123'

**Actual:**
Value above input is '000 123'

To fix you can just add `bubbles: true` in plugins dispatchEvents
For example here https://github.com/taiga-family/maskito/blob/main/projects/kit/src/lib/masks/number/plugins/leading-zeroes-validation.plugin.ts#L35C29-L35C29

### Maskito version

1.9.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
@aktanoff
Thanks for your research! 

I think we can create utility  `maskitoUpdateValue` (`@maskito/kit`)

```ts
export function maskitoUpdateValue(
    element: HTMLInputElement | HTMLTextAreaElement,
    value: string,
): void {
    element.value = value;
    element.dispatchEvent(
        new Event(
            'input',
            /**
             * Good explanation why we need it
             */
            {bubbles: true},
        ),
    );
}
```

And use it everywhere inside all plugins.
@aktanoff Do you want to contribute to our project ?

**Comment by nsbarsukov** [comment]
`maskitoUpdateValue` or `maskitoSetElementValue` ? 🤔

**Comment by aktanoff** [comment]
@nsbarsukov,
thanks for answer!
yeah, i can contribute, but did i got it right?
we need to write the utility, export it outside of the package, and replace with it all `dispatchEvents` calls in `@maskito/kit` plugins?

**Comment by nsbarsukov** [comment]
> we need to write the utility, export it outside of the package, and replace with it all dispatchEvents calls in @maskito/kit plugins?

@aktanoff yep, all's right)

I will really appreciate if you also add a simple unit test for react package (inside this [folder](https://github.com/taiga-family/maskito/tree/main/projects/react/src/lib/tests)) for this case. But it is optional, if you will have enough time for it.

**Comment by waterplea** [comment]
> `maskitoUpdateValue` or `maskitoSetElementValue` ? 🤔
> 
> **UPDATE:** i think that the second option is better
> 
> What do you think ?

I like `maskitoUpdateValue` better, since it does not just set value but updates everybody through event. And also it is shorter, 4 words seem too long to me :)

**Comment by nsbarsukov** [comment]
> I like `maskitoUpdateValue` better, since it does not just set value but updates everybody through event. And also it is shorter, 4 words seem too long to me :)

I agree that `maskitoSetElementValue` is too long.
However, `maskitoUpdateValue` is not enough descriptive – it is not obvious that it updates native element value (and not internal `Maskito`'s value or something else).

I have one more proposal – `maskitoUpdateElement`:

```ts
import {ElementState} from '../types';

export function maskitoUpdateElement(
    element: HTMLInputElement | HTMLTextAreaElement,
    valueOrElementState: ElementState | string,
): void {
    if (typeof valueOrElementState === 'string') {
        element.value = valueOrElementState;
    } else {
        const [from, to] = valueOrElementState.selection;

        element.value = valueOrElementState.value;
        element.setSelectionRange?.(from, to);
    }

    element.dispatchEvent(
        new Event(
            'input',
            /**
             * Good explanation why we need it
             */
            {bubbles: true},
        ),
    );
}
```

___

For example, we can use it here:
https://github.com/taiga-family/maskito/blob/39228debcc66ccccd4094f592f7e40450b493151/projects/core/src/lib/utils/initial-calibration-plugin.ts#L11-L13

```ts
maskitoUpdateElement(element, {
    value: maskitoTransform(element.value, customOptions || options),
    selection: [from, to],
});
```

___

@waterplea @aktanoff what do you think about it ?

**Comment by splincode** [comment]
`maskitoSetElementValue` +1

**Comment by nsbarsukov** [comment]
`maskitoUpdateElement` +1
