### ISSUE TITLE
🚀 - Add `deleteWordBackward` & `deleteWordForward` support

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/maskito#84]
### Which package(s) are relevant/related to the feature request?

@maskito/core

### Description

Delete a word directly before the caret position:
- `Ctrl` + `Backspace` (windows)
- `Option` + `Backspace` (mac os)

https://github.com/Tinkoff/maskito/blob/e5b40d1a05e1072ddc7735c82e276c0817526baf/projects/core/src/lib/mask.ts#L58

<br />

Delete a word directly after the caret position:
- `Ctrl` + `Backspace` (windows)
- `Option` + `Fn` + `Backspace` (mac os)
https://github.com/Tinkoff/maskito/blob/e5b40d1a05e1072ddc7735c82e276c0817526baf/projects/core/src/lib/mask.ts#L62

Read more: https://w3c.github.io/input-events/#interface-InputEvent-Attributes

**Comment by waterplea** [comment]
I believe it's Ctrl, not Alt 🙂

**Comment by nsbarsukov** [comment]
> I believe it's Ctrl, not Alt 🙂

Thanks, I've updated the description
