### ISSUE TITLE
🚀 - Formatting when pasting from the clipboard 

### ISSUE THREAD

**Issue by yumadilovtimur** [taiga-family/maskito#845]
### Which package(s) are relevant/related to the feature request?

@maskito/core, @maskito/kit

### Description

https://stackblitz.com/edit/flftyp-sm1g9b?file=mask.ts

```
import {maskitoDateTimeOptionsGenerator} from '@maskito/kit';

export default maskitoDateTimeOptionsGenerator({
    dateMode: 'dd/mm/yyyy',
    timeMode: 'HH:MM',
    dateSeparator: '.',
});
```

1. Copy the clipboard text "is my 1231990 birthday" (ctrl/cmd + C) -> Paste the text into input from the clipboard (ctrl/cmd + V) -> Result: "". Expected result: "12.03.1990".
2. Copy the clipboard text "1foo2bar456" (ctrl/cmd + C) -> Paste the text into input from the clipboard (ctrl/cmd + V) -> Result: "12.04.6". Expected result: "12.04.56".
3. Copy the clipboard text "34hel21llooo40abcc" (ctrl/cmd + C) -> Paste the text into input from the clipboard (ctrl/cmd + V) -> Result: "30.02.40". Expected result: "03.04.2140".

**Comment by nsbarsukov** [comment]
@yumadilovtimur Thanks for your proposal!

Unfortunately, these cases are rather controversial and can be interpreted differently by different people.

Let me explain it using your first case with paste of `1231990`.
At the first glance, I read it as `1231990 => 12.31.990 => the 31st month does not exist => prevent action`.
Further, I understood that your opinion is `1231990 => pad zero before 3 => 12.03.1990`.

Unfortunately, the attempts to "guess" the such specific cases can bring more bugs than any benefits.
That is why we are not going to implement the such behaviour in built-it `Date`-mask.

___

However, feel free to augment the built-in mask `Date` with any custom logic!
Just use `preprocessor` / `postprocessor`:

```ts
import { MaskitoOptions, MaskitoPostprocessor } from '@maskito/core';
import {maskitoDateOptionsGenerator} from '@maskito/kit';

const dateOptions = maskitoDateOptionsGenerator({mode: 'yyyy/mm/dd', separator: '/'});

const yourCustomPostProcessor: MaskitoPostprocessor = ({value, selection}) => {
  // put your logic inside
}

const options: MaskitoOptions = {
  ...dateOptions,
  postprocessors: [
    ...dateOptions.postprocessors,
    yourCustomPostProcessor,
  ]

}
```

Learn more:
https://maskito.dev/core-concepts/processors
