### ISSUE TITLE
🚀 - New plugin to enable validation on every keystroke for composition event (IME)

### ISSUE THREAD

**Issue by glebcha** [taiga-family/maskito#858]
### Playground Link

https://stackblitz.com/edit/maskito-article-demo?file=index.ts

### Description

https://github.com/taiga-family/.github/assets/2785780/6fe93a2f-b4d1-4fda-bcc8-85fad768745c

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [X] Android

**Comment by nsbarsukov** [comment]
@glebcha Hello!

I hope that this bug was fixed in [1.5.0](https://github.com/taiga-family/maskito/releases/tag/v1.5.0) release.
I've updated Maskito's version in the stackblitz's article (`1.0.0` => `1.9.0`).
Could you check it again ?

**Comment by glebcha** [comment]
> @glebcha Hello!
> 
> I hope that this bug was fixed in [1.5.0](https://github.com/taiga-family/maskito/releases/tag/v1.5.0) release.
> I've updated Maskito's version in the stackblitz's article (`1.0.0` => `1.9.0`).
> Could you check it again ?

But there is another sort of bug with 1.9.0.
First enter letters, then enter numbers and only then any special character.....input will be cleared of any non-digit characters. 
Android 14, latest Chrome version, Samsung S23.

**Comment by glebcha** [comment]
Anyone faced this issue, be aware of https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent.
I mean this behavior is expected when tou have autocomplete enabled and not yet selected one of proposed autocompletion variants or pressed space to follow shadowed input value.
@nsbarsukov I guess better add this to official documentation and "readme".

**Comment by nsbarsukov** [comment]
## Problem
Some Androids always interprets their input as [`CompositionEvent`](https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent).
`Maskito` will validate their input when `compositionend`-event is fired.

By default, `Maskito` does not break IME Composition (wait until it ends to calibrate value).
Maskito behaves in this way now (no changes are required).

It is default behaviour for other popular mask library too: `imask`, `ngx-mask`.
On another side, another popular legacy library – `text-mask` can break IME if intermediate value does not satisfy mask's constraint.

## Discussion
There is not right-solution for this case.
If we validate intermediate composition's value on every keystroke => we break core concept of IME (Japanese, Chinese and etc).
If we don't validate intermediate composition's value on every keystroke => `Maskito` waits until it will finish => Sometimes it is not required (for example, input of numbers).

## Proposed solution
By default, `Maskito` does not break IME Composition (wait until it ends to calibrate value).
Introduce `maskitoCompositionValidationPlugin` => developer can use it to enable validation of intermediate value of composition event.

```ts
import {maskitoCompositionValidationPlugin, MaskitoOptions} from '@maskito/core';

export default {
    mask: /^[0-9０-９]*$/,
    plugins: [maskitoCompositionValidationPlugin()],
} as MaskitoOptions;

```

**Comment by nsbarsukov** [comment]
What is better and more self-descriptive: `maskitoCompositionValidationPlugin` or `maskitoStrictCompositionPlugin ` ? 🤔
