### ISSUE TITLE
🐞 - Typing multiple full width numbers will delete original value

### ISSUE THREAD

**Issue by rikusen0335** [taiga-family/maskito#866]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/stackblitz-starters-xygfc2?file=src%2FApp.tsx

### Description

For ease I'm gonna explain it with video.
This↓ will help you understand.

https://github.com/taiga-family/maskito/assets/19174234/f2240c8d-08a2-4804-b570-9e811b13e712

### Maskito version

1.9.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge
_Additional Info: Chromium Edge, not old one_

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by rikusen0335** [comment]
This probably being closed when #864 fixed.

**Comment by nsbarsukov** [comment]
@rikusen0335 Should we close this issue (#864 was merged) ?

**Comment by rikusen0335** [comment]
Oh yes
