### ISSUE TITLE
🐞 - `min` is not working of `maskitoNumberOptionsGenerator`

### ISSUE THREAD

**Issue by rikusen0335** [taiga-family/maskito#867]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/stackblitz-starters-vhktps?file=src%2FMaskitoInput.tsx

### Description

After open stackblitz and do this:
Typeing lots of numbers inside input, and then backspace all won't limit to 500 which is constant MIN value I set.

max is working as I expect.

### Maskito version

1.9.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge
_Additional Info: Chromium Edge, not old one_

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
Hello!

Read these comments to understand why
https://github.com/taiga-family/maskito/blob/0a12dee16c931c1d6d02f1cf4cafe49379b03312/projects/kit/src/lib/masks/number/processors/min-max-postprocessor.ts#L22-L32

https://github.com/taiga-family/maskito/blob/0a12dee16c931c1d6d02f1cf4cafe49379b03312/projects/kit/src/lib/masks/number/plugins/min-max.plugin.ts#L7-L11

**Comment by rikusen0335** [comment]
Got it, thank you!
