### ISSUE TITLE
🚀 - Add full-width numbers support for `Time`, `Date`, `DateTime`, `DateRange`

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/maskito#884]
### Which package(s) are relevant/related to the feature request?

@maskito/kit

### Description

1. Move [`toHalfWidthNumber`](https://github.com/taiga-family/maskito/blob/main/projects/kit/src/lib/masks/number/utils/to-half-width-number.ts) to [`projects/kit/src/lib/utils`](https://github.com/taiga-family/maskito/tree/main/projects/kit/src/lib/utils).

2. Move [`createFullWidthToHalfWidthPreprocessor`](https://github.com/taiga-family/maskito/blob/main/projects/kit/src/lib/masks/number/processors/fullwidth-to-halfwidth-preprocessor.ts) to [`projects/kit/src/lib/processors`](https://github.com/taiga-family/maskito/tree/main/projects/kit/src/lib/processors).

3. And add `createFullWidthToHalfWidthPreprocessor` to  [`Time`](https://maskito.dev/kit/time), [`Date`](https://maskito.dev/kit/date), [`DateRange`](https://maskito.dev/kit/date-range), [`DateTime`](https://maskito.dev/kit/date-time).

4. Add Cypress Tests for full-width cases

Learn more:
* https://github.com/taiga-family/maskito/pull/864#discussion_r1447423820

**Comment by nsbarsukov** [comment]
@rikusen0335 just mention you here to have possibility to assign you to this issue.

**Comment by nsbarsukov** [comment]
@rikusen0335 ops, i cannot assign you until you write something here 😄

**Comment by rikusen0335** [comment]
Oops I wrote something now
