### ISSUE TITLE
🚀 - Angular Standalone Directive not exist in latest package

### ISSUE THREAD

**Issue by pumano** [taiga-family/maskito#893]
### Which package(s) are relevant/related to the feature request?

@maskito/angular

### Description

Documentation website require to import Standalone MaskitoDirective, while latest package does not have one, only module provided.

Would love if current main branch will be released as new version.

**Comment by waterplea** [comment]
Yes, it's coming soon this month

**Comment by nsbarsukov** [comment]
@pumano
https://maskito.dev has been updated. Now it contains only the last **published** public API.

New version Maskito `2.0.0` will be published later. Probably in 1-2 weeks.
