### ISSUE TITLE
🐞 - No need to execute `setSelectionRange` if element is not focused

### ISSUE THREAD

**Issue by MehdiRhifar** [taiga-family/maskito#929]
### Which package(s) are the source of the bug?

@maskito/core, @maskito/kit, @maskito/react

### Playground Link

https://stackblitz.com/edit/stackblitz-starters-4s7lyp?file=src%2FNumberInput.tsx

### Description

When I add a postfix in maskitoNumberOptionsGenerator (but I think it also appends if I add a postfix manually through postProcess), the input gains focus without any action.

I have only seen this in the mobile version because the keyboard opens automatically. You can try it using the StackBlitz link; go to the application link on a mobile device.

### Maskito version

1.9.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
@MehdiRhifar Thanks for your bug reproduction!

This issue relates to the initial calibration of Maskito (when initial value does not satisfy mask constraints).
The **temporary** workaround for you: don't set invalid initial value for `<input />`.

**Comment by nsbarsukov** [comment]
The new minimum bug reproduction:
https://stackblitz.com/edit/initial-focus-bug

P.S. use real mobile device
