### ISSUE TITLE
🐞 - Add configurable parameter `minusSign` to `Number`

### ISSUE THREAD

**Issue by framasev** [taiga-family/maskito#969]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/angular-8ndsd9?file=src%2Fmain.ts

### Description

When using the `maskitoNumberOptionsGenerator` mask, hyphen minus (`U+002d`) is transformed to minus sign (`U+2212`) causing coercion errors:

```typescript
// masked: 8722
console.log('masked: ', maskitoTransform('-1', maskitoNumberOptionsGenerator()).charCodeAt(0)); 
// unmasked: 45
console.log('unmasked: ', '-1'.charCodeAt(0));

// masked to number: NaN
console.log('masked to number: ', Number(maskitoTransform('-1', maskitoNumberOptionsGenerator())));
// unmsaked to number: -1
console.log('unmsaked to number: ', Number('-1'));
```

For example, these custom validators causing errors because of `NaN` (and in a server side - `illegal character`):
```typescript
export class NumberValidators {
  static number({ value }: AbstractControl) {
    return NumberValidators.isNumber(value)
      ? null
      : { notNumber: `${value} is not a number` };
  }

  static integer({ value }: AbstractControl) {
    return NumberValidators.isInteger(value)
      ? null
      : {
          notInteger: `${value} is not an integer`,
        };
  }

  static natural({ value }: AbstractControl) {
    return NumberValidators.isNumber(value) &&
      NumberValidators.isInteger(value) &&
      value > 0
      ? null
      : { notNaturalNumber: `${value} is not a natural number` };
  }

  static whole({ value }: AbstractControl) {
    return NumberValidators.isNumber(value) &&
      NumberValidators.isInteger(value) &&
      value >= 0
      ? null
      : { notWholeNumber: `${value} is not an whole number` };
  }

  static positive({ value }: AbstractControl) {
    return NumberValidators.isNumber(value) && value > 0
      ? null
      : { notPositiveNumber: `${value} is not a positive number` };
  }

  private static isNumber(num: number | string): boolean {
    return Number.isNaN(Number(num)) === false;
  }

  private static isInteger(num: number | string): boolean {
    return Number.isInteger(Number(num));
  }
}
```

See https://github.com/tc39/proposals/issues/37.

### Maskito version

2.0.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
Use `maskitoParseNumber` to parse masked string

<img width="1053" alt="Screenshot 2024-01-30 at 15 40 40" src="https://github.com/taiga-family/maskito/assets/35179038/7f44f1e4-73ab-47a0-ad00-67ff9f129d7a">

**Comment by framasev** [comment]
@nsbarsukov I would like to use `maskitoNumberOptionsGenerator` to create and apply mask to input without manual parsing of input value. The input value should be a valid number by default.

**Comment by nsbarsukov** [comment]
@framasev okey, we will add configurable parameter `minusSign` to `maskitoNumberOptionsGenerator` 👌 

```ts
import {maskitoNumberOptionsGenerator} from '@maskito/kit';

const options = maskitoNumberOptionsGenerator({
    minusSign: '-',
});

```

It will be remain `CHAR_MINUS` as default value. 
But developer will be able replace it with any value.

**Comment by waterplea** [comment]
Your numeric validators wouldn't work as expected anyway, though, because they will be unable to parse thousand separators: `Number('10 728.90') -> NaN`.

**Comment by framasev** [comment]
@waterplea You are right. In any case, disabling the formatting of thousandSeparator is an option, unlike the formatting of the minus sign.

Regarding the masking directive, does it support different values for the model and the displayed value in the input, relying, for example, on flags like `emitModelToViewChange` and `emitViewToModelChange` in the implementation? This way, we could maintain accessibility and typographic correctness while preserving the validity of the underlying value.

**Comment by waterplea** [comment]
Generally speaking it's impossible to maintain a masked and unmasked couple, and current directive is the general one. A dedicated number directive can easily be implemented extending [default accessor](https://angular.io/api/forms/DefaultValueAccessor):
https://stackblitz.com/edit/maskito-number-input

**Comment by nsbarsukov** [comment]
Closed by https://github.com/taiga-family/maskito/pull/1118
