### ISSUE TITLE
🐞 - `@maskito/react` does not include `umd`-format

### ISSUE THREAD

**Issue by a88zach** [taiga-family/maskito#983]
### Which package(s) are the source of the bug?

@maskito/react

### Playground Link

x

### Description

The new version of @maskito/react is esm only.  Is this intentional or just a bug?  I don't see any thing in the release notes saying that this package is now esm only.

This is from the package.json in the distributed version from npm

```
 "module": "./index.esm.js",
  "type": "module",
  "main": "./index.esm.js"
```

### Maskito version

2.0.1

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by a88zach** [comment]
Likely related to https://github.com/taiga-family/maskito/issues/956

**Comment by nsbarsukov** [comment]
`@maskito/react@1.9.0` has `umd`-format:
<img width="870" alt="1 9 0" src="https://github.com/taiga-family/maskito/assets/35179038/e208ad3e-4928-47a4-ae2c-aacb427770f6">

___

`@maskito/react@2.0.0` does **not** have `umd`-format
<img width="870" alt="2 0 0" src="https://github.com/taiga-family/maskito/assets/35179038/8355c6fc-8696-4587-a3b1-ed8b70f2fa02">

___

It is `2.0.0`'s regression bug. Probably it is connected to `Nx` update.

**Comment by nsbarsukov** [comment]
@a88zach Thanks for bug report!
I will fix it soon.
